//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2019410clientapp.StudentServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private System.Nullable<int> ageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((this.StudentIDField.Equals(value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetStudentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        _2019410clientapp.StudentServiceReference1.GetStudentResponse GetStudent(_2019410clientapp.StudentServiceReference1.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.GetStudentResponse> GetStudentAsync(_2019410clientapp.StudentServiceReference1.GetStudentRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        _2019410clientapp.StudentServiceReference1.AddStudentResponse AddStudent(_2019410clientapp.StudentServiceReference1.AddStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.AddStudentResponse> AddStudentAsync(_2019410clientapp.StudentServiceReference1.AddStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudent", Namespace="http://tempuri.org/", Order=0)]
        public _2019410clientapp.StudentServiceReference1.GetStudentRequestBody Body;
        
        public GetStudentRequest() {
        }
        
        public GetStudentRequest(_2019410clientapp.StudentServiceReference1.GetStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentRequestBody {
        
        public GetStudentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2019410clientapp.StudentServiceReference1.GetStudentResponseBody Body;
        
        public GetStudentResponse() {
        }
        
        public GetStudentResponse(_2019410clientapp.StudentServiceReference1.GetStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2019410clientapp.StudentServiceReference1.Student[] GetStudentResult;
        
        public GetStudentResponseBody() {
        }
        
        public GetStudentResponseBody(_2019410clientapp.StudentServiceReference1.Student[] GetStudentResult) {
            this.GetStudentResult = GetStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudent", Namespace="http://tempuri.org/", Order=0)]
        public _2019410clientapp.StudentServiceReference1.AddStudentRequestBody Body;
        
        public AddStudentRequest() {
        }
        
        public AddStudentRequest(_2019410clientapp.StudentServiceReference1.AddStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2019410clientapp.StudentServiceReference1.Student s;
        
        public AddStudentRequestBody() {
        }
        
        public AddStudentRequestBody(_2019410clientapp.StudentServiceReference1.Student s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2019410clientapp.StudentServiceReference1.AddStudentResponseBody Body;
        
        public AddStudentResponse() {
        }
        
        public AddStudentResponse(_2019410clientapp.StudentServiceReference1.AddStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddStudentResult;
        
        public AddStudentResponseBody() {
        }
        
        public AddStudentResponseBody(bool AddStudentResult) {
            this.AddStudentResult = AddStudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : _2019410clientapp.StudentServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<_2019410clientapp.StudentServiceReference1.WebService1Soap>, _2019410clientapp.StudentServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2019410clientapp.StudentServiceReference1.GetStudentResponse _2019410clientapp.StudentServiceReference1.WebService1Soap.GetStudent(_2019410clientapp.StudentServiceReference1.GetStudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public _2019410clientapp.StudentServiceReference1.Student[] GetStudent() {
            _2019410clientapp.StudentServiceReference1.GetStudentRequest inValue = new _2019410clientapp.StudentServiceReference1.GetStudentRequest();
            inValue.Body = new _2019410clientapp.StudentServiceReference1.GetStudentRequestBody();
            _2019410clientapp.StudentServiceReference1.GetStudentResponse retVal = ((_2019410clientapp.StudentServiceReference1.WebService1Soap)(this)).GetStudent(inValue);
            return retVal.Body.GetStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.GetStudentResponse> _2019410clientapp.StudentServiceReference1.WebService1Soap.GetStudentAsync(_2019410clientapp.StudentServiceReference1.GetStudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.GetStudentResponse> GetStudentAsync() {
            _2019410clientapp.StudentServiceReference1.GetStudentRequest inValue = new _2019410clientapp.StudentServiceReference1.GetStudentRequest();
            inValue.Body = new _2019410clientapp.StudentServiceReference1.GetStudentRequestBody();
            return ((_2019410clientapp.StudentServiceReference1.WebService1Soap)(this)).GetStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2019410clientapp.StudentServiceReference1.AddStudentResponse _2019410clientapp.StudentServiceReference1.WebService1Soap.AddStudent(_2019410clientapp.StudentServiceReference1.AddStudentRequest request) {
            return base.Channel.AddStudent(request);
        }
        
        public bool AddStudent(_2019410clientapp.StudentServiceReference1.Student s) {
            _2019410clientapp.StudentServiceReference1.AddStudentRequest inValue = new _2019410clientapp.StudentServiceReference1.AddStudentRequest();
            inValue.Body = new _2019410clientapp.StudentServiceReference1.AddStudentRequestBody();
            inValue.Body.s = s;
            _2019410clientapp.StudentServiceReference1.AddStudentResponse retVal = ((_2019410clientapp.StudentServiceReference1.WebService1Soap)(this)).AddStudent(inValue);
            return retVal.Body.AddStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.AddStudentResponse> _2019410clientapp.StudentServiceReference1.WebService1Soap.AddStudentAsync(_2019410clientapp.StudentServiceReference1.AddStudentRequest request) {
            return base.Channel.AddStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2019410clientapp.StudentServiceReference1.AddStudentResponse> AddStudentAsync(_2019410clientapp.StudentServiceReference1.Student s) {
            _2019410clientapp.StudentServiceReference1.AddStudentRequest inValue = new _2019410clientapp.StudentServiceReference1.AddStudentRequest();
            inValue.Body = new _2019410clientapp.StudentServiceReference1.AddStudentRequestBody();
            inValue.Body.s = s;
            return ((_2019410clientapp.StudentServiceReference1.WebService1Soap)(this)).AddStudentAsync(inValue);
        }
    }
}
